[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"

dependencies = [
  "python-telegram-bot>=20.0",
  "feedparser",
  "telegram==0.0.1",
  "requests>=2.32.3",
  "openai>=1.12.0"
]

